import 'package:flutter/material.dart';


const lightColorScheme = ColorScheme(
    brightness : Brightness.light,
    primary : Color(0xFF9D413F),
    onPrimary : Color(0xFFFFFFFF),
    primaryContainer : Color(0xFFFFDAD7),
    onPrimaryContainer : Color(0xFF410005),
    secondary : Color(0xFF775654),
    onSecondary : Color(0xFFFFFFFF),
    secondaryContainer : Color(0xFFFFDAD7),
    onSecondaryContainer : Color(0xFF2C1514),
    tertiary : Color(0xFF735B2E),
    onTertiary : Color(0xFFFFFFFF),
    tertiaryContainer : Color(0xFFFFDEA8),
    onTertiaryContainer : Color(0xFF271900),
    error : Color(0xFFBA1A1A),
    errorContainer : Color(0xFFFFDAD6),
    onError : Color(0xFFFFFFFF),
    onErrorContainer : Color(0xFF410002),
    background : Color(0xFFFFFBFF),
    onBackground : Color(0xFF201A1A),
    surface : Color(0xFFFFFBFF),
    onSurface : Color(0xFF201A1A),
    surfaceVariant : Color(0xFFF4DDDB),
    onSurfaceVariant : Color(0xFF534342),
    outline : Color(0xFF857371),
    onInverseSurface : Color(0xFFFBEEEC),
    inverseSurface : Color(0xFF362F2E),
    inversePrimary : Color(0xFFFFB3AF),
    shadow : Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
    brightness : Brightness.dark,
    primary : Color(0xFFFFB3AF),
    onPrimary : Color(0xFF601315),
    primaryContainer : Color(0xFF7E2A29),
    onPrimaryContainer : Color(0xFFFFDAD7),
    secondary : Color(0xFFE7BDBA),
    onSecondary : Color(0xFF442928),
    secondaryContainer : Color(0xFF5D3F3D),
    onSecondaryContainer : Color(0xFFFFDAD7),
    tertiary : Color(0xFFE2C28C),
    onTertiary : Color(0xFF402D05),
    tertiaryContainer : Color(0xFF594319),
    onTertiaryContainer : Color(0xFFFFDEA8),
    error : Color(0xFFFFB4AB),
    errorContainer : Color(0xFF93000A),
    onError : Color(0xFF690005),
    onErrorContainer : Color(0xFFFFDAD6),
    background : Color(0xFF201A1A),
    onBackground : Color(0xFFEDE0DE),
    surface : Color(0xFF201A1A),
    onSurface : Color(0xFFEDE0DE),
    surfaceVariant : Color(0xFF534342),
    onSurfaceVariant : Color(0xFFD8C2C0),
    outline : Color(0xFFA08C8B),
    onInverseSurface : Color(0xFF201A1A),
    inverseSurface : Color(0xFFEDE0DE),
    inversePrimary : Color(0xFF9D413F),
    shadow : Color(0xFF000000),
);
